const categories={event:{label:'Events',color:'#e85b98',icon:'⚡'},action:{label:'Actions',color:'#f39a3f',icon:'✦'},variable:{label:'Variables',color:'#18b89a',icon:'◆'},condition:{label:'Conditions',color:'#8567e8',icon:'◇'},loop:{label:'Loops',color:'#5d9ee5',icon:'↻'},logic:{label:'Logic',color:'#6f8eae',icon:'∴'},math:{label:'Math',color:'#6179aa',icon:'＋'},text:{label:'Text',color:'#54a995',icon:'T'},values:{label:'Values',color:'#19aa18',icon:'↔'},world:{label:'World',color:'#0879a9',icon:'◈'},roblox:{label:'Roblox',color:'#687687',icon:'◈'}};
const definitions={
 playerJoin:{type:'event',label:'jogador entrar',icon:'⚡',template:'Players.PlayerAdded:Connect(function(player)',props:{},children:true},
 playerLeave:{type:'event',label:'jogador sair',icon:'⚡',template:'Players.PlayerRemoving:Connect(function(player)',props:{},children:true},
 gameStart:{type:'event',label:'jogo iniciar',icon:'⚡',template:'local function onGameStart()',props:{},children:true},
 partTouched:{type:'event',label:'Part tocada',icon:'⚡',template:'part.Touched:Connect(function(hit)',props:{part:'Part'},children:true},
 wait:{type:'action',label:'esperar',icon:'◷',template:'task.wait({seconds})',props:{seconds:'2'},propsMeta:{seconds:['Segundos','number']}},
 print:{type:'action',label:'imprimir',icon:'✦',template:'print({text})',props:{text:'Coins'},propsMeta:{text:['Texto','text']}},
 setVar:{type:'action',label:'definir',icon:'◆',template:'{name} = {value}',props:{name:'Coins',value:'0'},propsMeta:{name:['Variável','text'],value:['Valor','text']}},
 add:{type:'action',label:'adicionar',icon:'＋',template:'{name} += {value}',props:{name:'Coins',value:'10'},propsMeta:{name:['Variável','text'],value:['Valor','text']}},
 remove:{type:'action',label:'remover',icon:'−',template:'{name} -= {value}',props:{name:'Coins',value:'1'},propsMeta:{name:['Variável','text'],value:['Valor','text']}},
 createVar:{type:'variable',label:'criar variável',icon:'◆',template:'local {name} = {value}',props:{name:'Coins',value:'0',valueType:'Número'},propsMeta:{name:['Nome','text'],value:['Valor','text'],valueType:['Tipo','type']}},
 useVar:{type:'variable',label:'usar variável',icon:'◆',template:'{name}',props:{name:'Coins'},propsMeta:{name:['Nome','text']}},
 if:{type:'condition',label:'SE',icon:'◇',template:'if {left} {operator} {right} then',props:{left:'Coins',operator:'=',right:'0'},propsMeta:{left:['Valor A','text'],operator:['Operador','operator'],right:['Valor B','text']},children:true},
 else:{type:'condition',label:'SENÃO',icon:'◇',template:'else',props:{},children:true},
 repeat:{type:'loop',label:'repetir vezes',icon:'↻',template:'for _ = 1, {times} do',props:{times:'3'},propsMeta:{times:['Repetições','number']},children:true},
 while:{type:'loop',label:'enquanto',icon:'↻',template:'while {condition} do',props:{condition:'Coins > 0'},propsMeta:{condition:['Condição','text']},children:true},
 loopRepeatFrom:{type:'loop',label:'repeat variable_count value from start to end',icon:'↻',template:'for {variable} = {start}, {end} do',props:{variable:'i',start:'1',end:'10'},propsMeta:{variable:['Variable','text'],start:['Start','number'],end:['End','number']},children:true},
 loopChildren:{type:'loop',label:'loop through children of instance',icon:'↻',template:'for _, {child} in {instance}:GetChildren() do',props:{instance:'workspace',child:'child'},propsMeta:{instance:['Instance','text'],child:['Variable','text']},children:true},
 loopDescendants:{type:'loop',label:'loop through descendants of instance',icon:'↻',template:'for _, {descendant} in {instance}:GetDescendants() do',props:{instance:'workspace',descendant:'descendant'},propsMeta:{instance:['Instance','text'],descendant:['Variable','text']},children:true},
 loopBreak:{type:'loop',label:'break this loop',icon:'↪',template:'break',props:{}},
 logicWait:{type:'logic',label:'esperar',icon:'◷',template:'task.wait({seconds})',props:{seconds:'2'},propsMeta:{seconds:['Segundos','number','socket']}},
 logicIf:{type:'logic',label:'se',icon:'◇',template:'if {condition} then',props:{condition:'condition'},propsMeta:{condition:['Condição','text','socket']},children:true},
 logicNot:{type:'logic',label:'não',icon:'¬',template:'not {value}',props:{value:'any'},propsMeta:{value:['Valor','text','socket']}},
 logicEqual:{type:'logic',label:'qualquer = qualquer',icon:'=',template:'{left} == {right}',props:{left:'any',right:'any'},propsMeta:{left:['Valor A','text','socket'],right:['Valor B','text','socket']}},
 logicLess:{type:'logic',label:'qualquer < qualquer',icon:'<',template:'{left} < {right}',props:{left:'any',right:'any'},propsMeta:{left:['Valor A','text','socket'],right:['Valor B','text','socket']}},
 logicGreater:{type:'logic',label:'qualquer > qualquer',icon:'>',template:'{left} > {right}',props:{left:'any',right:'any'},propsMeta:{left:['Valor A','text','socket'],right:['Valor B','text','socket']}},
 logicNotEqual:{type:'logic',label:'qualquer ~= qualquer',icon:'≠',template:'{left} ~= {right}',props:{left:'any',right:'any'},propsMeta:{left:['Valor A','text','socket'],right:['Valor B','text','socket']}},
 logicTrue:{type:'logic',label:'verdadeiro',icon:'●',template:'true',props:{}},
 logicFalse:{type:'logic',label:'falso',icon:'●',template:'false',props:{}},
 mathNumber:{type:'math',label:'number',icon:'●',template:'{value}',props:{value:'0'},propsMeta:{value:['Número','number']}},
 mathValue:{type:'math',label:'num.',icon:'●',template:'{value}',props:{value:'0'},propsMeta:{value:['Número','number']}},
 mathAdd:{type:'math',label:'num. 1 + num. 2',icon:'＋',template:'{left} + {right}',props:{left:'0',right:'0'},propsMeta:{left:['Número 1','number','socket'],right:['Número 2','number','socket']}},
 mathMultiplyAdd:{type:'math',label:'num. × 2 + 1',icon:'×',template:'{value} * 2 + 1',props:{value:'0'},propsMeta:{value:['Número','number','socket']}},
 mathAddMultiply:{type:'math',label:'1 + 2 × num.',icon:'×',template:'1 + 2 * {value}',props:{value:'0'},propsMeta:{value:['Número','number','socket']}},
 textString:{type:'text',label:'string ""',icon:'T',template:'"{value}"',props:{value:''},propsMeta:{value:['Texto','text']}},
 textValue:{type:'text',label:'""',icon:'T',template:'"{value}"',props:{value:''},propsMeta:{value:['Texto','text']}},
 textJoin:{type:'text',label:'join string 1 with string 2',icon:'↔',template:'{left} .. {right}',props:{left:'"string 1"',right:'"string 2"'},propsMeta:{left:['String 1','text','socket'],right:['String 2','text','socket']}},
 valueToString:{type:'values',label:'any to string',icon:'↔',template:'tostring({value})',props:{value:'any'},propsMeta:{value:['Valor','text','socket']}},
 valueToNumber:{type:'values',label:'any to number',icon:'↔',template:'tonumber({value})',props:{value:'any'},propsMeta:{value:['Valor','text','socket']}},
 valueVariable:{type:'variable',label:'var.',icon:'◆',template:'{name}',props:{name:'x'},propsMeta:{name:['Variável','text']}},
 worldMe:{type:'world',label:'me',icon:'●',template:'player',props:{}},
 worldScript:{type:'world',label:'script',icon:'●',template:'script',props:{}},
 worldInstance:{type:'world',label:'ins. instance',icon:'◈',template:'{instance}',props:{instance:'instance'},propsMeta:{instance:['Instance','text','socket']}},
 worldVector3:{type:'world',label:'vec3 x y z',icon:'◆',template:'Vector3.new({x}, {y}, {z})',props:{x:'0',y:'0',z:'0'},propsMeta:{x:['X','number','socket'],y:['Y','number','socket'],z:['Z','number','socket']}},
 worldSetProperty:{type:'world',label:'set property of instance to value',icon:'◆',template:'{instance}.{property} = {value}',props:{property:'property',instance:'instance',value:'value'},propsMeta:{property:['Property','text'],instance:['Instance','text','socket'],value:['Value','text','socket']}},
 worldGetProperty:{type:'world',label:'property of instance',icon:'◆',template:'{instance}.{property}',props:{property:'property',instance:'instance'},propsMeta:{property:['Property','text'],instance:['Instance','text','socket']}},
 worldFind:{type:'world',label:'find string in instance',icon:'⌕',template:'{instance}:FindFirstChild({text})',props:{text:'string',instance:'instance'},propsMeta:{text:['String','text','socket'],instance:['Instance','text','socket']}},
 worldColor3Rgb:{type:'world',label:'color 3 r (number) g (number) b (number)',icon:'●',template:'Color3.fromRGB({r}, {g}, {b})',props:{r:'0',g:'0',b:'0'},propsMeta:{r:['R','number','socket'],g:['G','number','socket'],b:['B','number','socket']}},
 worldColor3:{type:'world',label:'color3 0 255 0',icon:'●',template:'Color3.fromRGB({r}, {g}, {b})',props:{r:'0',g:'255',b:'0'},propsMeta:{r:['R','number'],g:['G','number'],b:['B','number']}},
 worldCreate:{type:'world',label:'create ClassName in instance var. _instance',icon:'＋',template:'local {variable} = Instance.new("{className}", {instance})',props:{className:'Part',instance:'workspace',variable:'_instance'},propsMeta:{className:['ClassName','text'],instance:['Instance','text','socket'],variable:['Variable','text']}},
 worldClone:{type:'world',label:'clone instance var. _clone',icon:'⧉',template:'local {variable} = {instance}:Clone()',props:{instance:'instance',variable:'_clone'},propsMeta:{instance:['Instance','text','socket'],variable:['Variable','text']}},
 player:{type:'roblox',label:'Player',icon:'◈',template:'player',props:{},children:false},
 character:{type:'roblox',label:'Character',icon:'◈',template:'player.Character',props:{},children:false},
 humanoid:{type:'roblox',label:'Humanoid',icon:'◈',template:'character:FindFirstChildOfClass("Humanoid")',props:{},children:false},
 workspace:{type:'roblox',label:'Workspace',icon:'◈',template:'workspace',props:{},children:false},
 part:{type:'roblox',label:'Part',icon:'◈',template:'part',props:{name:'Part'},propsMeta:{name:['Nome','text']},children:false}
};
const libraryOrder=['playerJoin','playerLeave','gameStart','partTouched','wait','print','setVar','add','remove','createVar','useVar','if','else','repeat','while','loopRepeatFrom','loopChildren','loopDescendants','loopBreak','logicWait','logicIf','logicNot','logicEqual','logicLess','logicGreater','logicNotEqual','logicTrue','logicFalse','mathNumber','mathValue','mathAdd','mathMultiplyAdd','mathAddMultiply','textString','textValue','textJoin','valueToString','valueToNumber','valueVariable','worldMe','worldScript','worldInstance','worldVector3','worldSetProperty','worldGetProperty','worldFind','worldColor3Rgb','worldColor3','worldCreate','worldClone','player','character','humanoid','workspace','part'];
const englishLabels={playerJoin:'player joined',playerLeave:'player left',gameStart:'game started',partTouched:'Part touched',wait:'wait',print:'print',setVar:'set',add:'add',remove:'remove',createVar:'create variable',useVar:'use variable',if:'if',else:'else',repeat:'repeat times',while:'while',loopRepeatFrom:'repeat variable_count value from start to end',loopChildren:'loop through children of instance',loopDescendants:'loop through descendants of instance',loopBreak:'break this loop',logicWait:'wait',logicIf:'if',logicNot:'not',logicEqual:'any = any',logicLess:'any < any',logicGreater:'any > any',logicNotEqual:'any ~= any',logicTrue:'true',logicFalse:'false',mathNumber:'number',mathValue:'num.',mathAdd:'num. 1 + num. 2',mathMultiplyAdd:'num. × 2 + 1',mathAddMultiply:'1 + 2 × num.',textString:'string ""',textValue:'""',textJoin:'join string 1 with string 2',valueToString:'any to string',valueToNumber:'any to number',valueVariable:'var.',worldMe:'me',worldScript:'script',worldInstance:'ins. instance',worldVector3:'vec3 x y z',worldSetProperty:'set property of instance to value',worldGetProperty:'property of instance',worldFind:'find string in instance',worldColor3Rgb:'color 3 r (number) g (number) b (number)',worldColor3:'color3 0 255 0',worldCreate:'create ClassName in instance var. _instance',worldClone:'clone instance var. _clone',player:'Player',character:'Character',humanoid:'Humanoid',workspace:'Workspace',part:'Part'};
const portugueseLabels={playerJoin:'jogador entrou',playerLeave:'jogador saiu',gameStart:'jogo iniciou',partTouched:'Part tocada',setVar:'definir',add:'adicionar',remove:'remover',createVar:'criar variável',useVar:'usar variável',if:'se',else:'senão',repeat:'repetir vezes',while:'enquanto',loopRepeatFrom:'repetir variável quantidade do início ao fim',loopChildren:'percorrer filhos da instância',loopDescendants:'percorrer descendentes da instância',loopBreak:'interromper este loop',logicIf:'se',logicNot:'não',logicEqual:'qualquer = qualquer',logicLess:'qualquer < qualquer',logicGreater:'qualquer > qualquer',logicNotEqual:'qualquer ~= qualquer',logicTrue:'verdadeiro',logicFalse:'falso',mathNumber:'número',mathValue:'núm.',mathAdd:'núm. 1 + núm. 2',mathMultiplyAdd:'núm. × 2 + 1',mathAddMultiply:'1 + 2 × núm.',textString:'texto ""',textValue:'""',textJoin:'juntar texto 1 com texto 2',valueToString:'qualquer para texto',valueToNumber:'qualquer para número',valueVariable:'var.',worldMe:'eu',worldScript:'script',worldInstance:'inst. instância',worldVector3:'vec3 x y z',worldSetProperty:'definir propriedade da instância com valor',worldGetProperty:'propriedade da instância',worldFind:'encontrar texto na instância',worldColor3Rgb:'cor 3 r (número) g (número) b (número)',worldColor3:'cor3 0 255 0',worldCreate:'criar ClassName na instância var. _instance',worldClone:'clonar instância var. _clone',player:'Jogador',character:'Personagem',humanoid:'Humanoid',workspace:'Workspace',part:'Part'};
const portugueseCategories={event:'Eventos',action:'Ações',variable:'Variáveis',condition:'Condições',loop:'Loops',logic:'Lógica',math:'Matemática',text:'Texto',values:'Valores',world:'Mundo',roblox:'Roblox'};
let state={tree:[],selected:null,category:'event',zoom:100,grid:true,history:[],future:[],language:'en',inlineCode:true,theme:'light'};
const $=id=>document.getElementById(id); const clone=o=>JSON.parse(JSON.stringify(o));
function labelFor(key){return state.language==='pt'?(portugueseLabels[key]||definitions[key]?.label||key):(englishLabels[key]||definitions[key]?.label||key)}
function categoryLabel(key){return state.language==='pt'?(portugueseCategories[key]||categories[key].label):categories[key].label}
function snapshot(){state.history.push(clone(state.tree));if(state.history.length>30)state.history.shift();state.future=[]}
function makeNode(key){const d=definitions[key];return{id:crypto.randomUUID(),type:key,properties:clone(d.props||{}),children:d.children?[]:undefined}}
function findNode(list,id,parent=null){for(const node of list){if(node.id===id)return{node,parent,list};if(node.children){const found=findNode(node.children,id,node);if(found)return found}}}
function getColor(key){return categories[definitions[key].type].color}
const typingGame={phrases:['print("hello world")','local score = 0','if player then print("ready") end','for i = 1, 10 do print(i) end','task.wait(0.5)\nprint("loop")','local part = Instance.new("Part")','workspace.SpawnLocation.Position = Vector3.new(0, 5, 0)','if coins > 0 then coins -= 1 end'],current:'',input:'',score:0,correct:0,wrong:0,totalTyped:0,streak:0,comboHits:0,startTime:0,running:false,timer:null};
const typingAudio={ctx:null,memeFiles:['memes/faaah.mp3','memes/la-ele.mp3'],memeCache:[]};
function getTypingAudio(){if(!typingAudio.ctx){const Ctx=window.AudioContext||window.webkitAudioContext;typingAudio.ctx=Ctx?new Ctx():null}return typingAudio.ctx}
function playTypingTone(freq,type,duration,volume){const ctx=getTypingAudio();if(!ctx)return;const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.value=volume;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+duration);gain.gain.exponentialRampToValueAtTime(0.0001,ctx.currentTime+duration)}
function playTypingSuccess(){playTypingTone(660,'triangle',0.08,0.05);setTimeout(()=>playTypingTone(880,'triangle',0.1,0.05),80)}
function playTypingError(){playTypingTone(220,'sawtooth',0.12,0.05);setTimeout(()=>playTypingTone(180,'square',0.12,0.04),80)}
function getMemeAudioPool(){if(typingAudio.memeCache.length)return typingAudio.memeCache;typingAudio.memeCache=typingAudio.memeFiles.map(file=>{const audio=new Audio(file);audio.preload='auto';audio.volume=0.8;return audio});return typingAudio.memeCache}
function playComboMemeSound(){const pool=getMemeAudioPool();if(pool.length){const audio=pool[Math.floor(Math.random()*pool.length)];audio.currentTime=0;audio.play().catch(()=>{});return}const ctx=getTypingAudio();if(!ctx)return;const memeIndex=Math.floor(Math.random()*3);const now=ctx.currentTime;if(memeIndex===0){const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type='sawtooth';osc.frequency.setValueAtTime(180,now);osc.frequency.exponentialRampToValueAtTime(80,now+0.42);gain.gain.setValueAtTime(0.0001,now);gain.gain.exponentialRampToValueAtTime(0.12,now+0.02);gain.gain.exponentialRampToValueAtTime(0.0001,now+0.5);osc.connect(gain);gain.connect(ctx.destination);osc.start(now);osc.stop(now+0.5);setTimeout(()=>playTypingTone(120,'triangle',0.12,0.08),80);setTimeout(()=>playTypingTone(90,'triangle',0.18,0.07),170);}else if(memeIndex===1){const buffer=ctx.createBuffer(1,ctx.sampleRate*0.7,ctx.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const t=i/data.length;data[i]=(Math.random()*2-1)*Math.exp(-18*t);}const source=ctx.createBufferSource();const gain=ctx.createGain();source.buffer=buffer;gain.gain.setValueAtTime(0.0001,now);gain.gain.exponentialRampToValueAtTime(0.28,now+0.02);gain.gain.exponentialRampToValueAtTime(0.0001,now+0.7);source.connect(gain);gain.connect(ctx.destination);source.start(now);source.stop(now+0.7);setTimeout(()=>playTypingTone(50,'sine',0.2,0.1),40);setTimeout(()=>playTypingTone(35,'square',0.25,0.09),180);}else{[220,330,440,330,220].forEach((freq,idx)=>setTimeout(()=>playTypingTone(freq,'square',0.12,0.05),idx*90));}}
function openTypingHub(){document.getElementById('typingHub').classList.remove('hidden');document.getElementById('typingInput').focus();if(!typingGame.running){setTypingStatus('Pronto para começar. Clique em iniciar.');}}
function closeTypingHub(){document.getElementById('typingHub').classList.add('hidden');}
function renderTypingPrompt(){const text=typingGame.current;const current=typingGame.input;const spans=[];for(let i=0;i<text.length;i++){let cls='';if(i<current.length){cls=current[i]===text[i]?'correct':'wrong';}else if(i===current.length){cls='current';}spans.push(`<span class="char ${cls}">${escapeHtml(text[i])}</span>`);}document.getElementById('typingPrompt').innerHTML=spans.join('');}
function updateTypingStats(){const elapsedSeconds=Math.max((Date.now()-typingGame.startTime)/1000,1);const wpm=Math.max(0,Math.round((typingGame.correct/5)/(elapsedSeconds/60)));const accuracy=typingGame.totalTyped>0?Math.max(0,Math.round((typingGame.correct/(typingGame.correct+typingGame.wrong))*100)):100;document.getElementById('typingScore').textContent=String(typingGame.score);document.getElementById('typingSpeed').textContent=`${wpm} WPM`;document.getElementById('typingAccuracy').textContent=`${accuracy}%`;}
function setTypingStatus(message){document.getElementById('typingStatus').textContent=message;}
function resetTypingGame(){typingGame.current=typingGame.phrases[Math.floor(Math.random()*typingGame.phrases.length)];typingGame.input='';typingGame.score=0;typingGame.correct=0;typingGame.wrong=0;typingGame.totalTyped=0;typingGame.streak=0;typingGame.comboHits=0;typingGame.startTime=Date.now();typingGame.running=false;clearInterval(typingGame.timer);typingGame.timer=setInterval(()=>{if(typingGame.running){updateTypingStats()}},250);renderTypingPrompt();updateTypingStats();setTypingStatus('Pronto para começar. Clique em iniciar.');document.getElementById('typingInput').value='';document.getElementById('typingInput').focus();}
function startTypingGame(){if(typingGame.running){return;}typingGame.running=true;typingGame.startTime=Date.now();typingGame.score=Math.max(0,typingGame.score);setTypingStatus('Desafio em andamento! Digite com precisão.');document.getElementById('typingInput').value='';typingGame.input='';renderTypingPrompt();document.getElementById('typingInput').focus();updateTypingStats();}
function advanceTypingChallenge(){const bonus=Math.max(50,typingGame.current.length*12);typingGame.score += bonus + typingGame.streak*10;setTypingStatus(`Desafio concluído! +${bonus} pontos. Próxima frase...`);typingGame.current=typingGame.phrases[Math.floor(Math.random()*typingGame.phrases.length)];typingGame.input='';typingGame.correct += 1;typingGame.streak += 1;document.getElementById('typingInput').value='';renderTypingPrompt();updateTypingStats();playTypingSuccess();}
function handleTypingInput(event){if(!typingGame.running){startTypingGame();}const value=event.target.value;const target=typingGame.current;typingGame.input=value;const currentLength=Math.min(value.length,target.length);let localCorrect=0;let localWrong=0;for(let i=0;i<currentLength;i++){if(value[i]===target[i])localCorrect++;else localWrong++;}if(localWrong>0){typingGame.wrong += localWrong;typingGame.score=Math.max(0,typingGame.score-5);typingGame.streak=0;typingGame.comboHits=0;playTypingError();setTypingStatus('Erro detectado! Ajuste o ritmo e continue.');}else if(value.length>0){typingGame.correct += Math.max(0,value.length-localCorrect);typingGame.score += 2;typingGame.streak++;typingGame.comboHits++;playTypingSuccess();setTypingStatus('Resposta correta! Mantenha a sequência.');if(typingGame.comboHits>=5){typingGame.comboHits=0;playComboMemeSound();setTypingStatus('Combo x5! Meme ativado! +150 pontos.');typingGame.score+=150;}}typingGame.totalTyped=Math.max(typingGame.totalTyped,value.length);if(value===target){advanceTypingChallenge();}renderTypingPrompt();updateTypingStats();}
function bindTypingHub(){const openBtn=$('typingHubBtn');const closeBtn=$('closeTypingHub');const startBtn=$('startTypingBtn');const resetBtn=$('resetTypingBtn');const input=$('typingInput');if(openBtn)openBtn.onclick=openTypingHub;if(closeBtn)closeBtn.onclick=closeTypingHub;if(startBtn)startBtn.onclick=startTypingGame;if(resetBtn)resetBtn.onclick=resetTypingGame;if(input)input.oninput=handleTypingInput;document.addEventListener('keydown',e=>{if(e.key==='Escape' && $('typingHub') && !$('typingHub').classList.contains('hidden'))closeTypingHub();});}
function renderLibrary(){const tabs=Object.entries(categories).map(([key,c])=>`<button class="cat-tab ${state.category===key?'active':''}" data-cat="${key}">${categoryLabel(key)}</button>`).join('');$('categoryTabs').innerHTML=tabs;document.querySelectorAll('.cat-tab').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderLibrary()});const query=$('blockSearch').value.toLowerCase();const items=libraryOrder.filter(k=>definitions[k].type===state.category&&labelFor(k).toLowerCase().includes(query));$('libraryList').innerHTML=items.map(key=>{const d=definitions[key],c=categories[d.type];return`<div class="library-card" draggable="true" data-key="${key}"><div class="lib-icon" style="background:${c.color}">${d.icon}</div><div><strong>${labelFor(key)}</strong><span>${d.children?(state.language==='pt'?'bloco com área interna':'block with inner area'):(state.language==='pt'?'bloco de ação':'action block')}</span></div></div>`}).join('');document.querySelectorAll('.library-card').forEach(card=>{card.ondragstart=e=>e.dataTransfer.setData('block-key',card.dataset.key)})}
function blockMarkup(node,expression=false){const d=definitions[node.type],c=categories[d.type];let inside='';if(d.propsMeta){inside=Object.keys(d.propsMeta).map(key=>{const meta=d.propsMeta[key],val=node.properties[key];if(meta[2]==='socket')return`<span class="socket ${val&&typeof val==='object'?'socket-filled':''}" data-socket="${node.id}" data-prop="${key}">${val&&typeof val==='object'?blockMarkup(val,true):escapeHtml(val??meta[0])}</span>`;if(meta[1]==='operator'||meta[1]==='type'){const options=meta[1]==='type'?['Número','Texto','Boolean']:['=','>','<','>=','<='];return`<select data-prop="${key}">${options.map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('')}</select>`}return`<input data-prop="${key}" value="${escapeHtml(val??'')}" aria-label="${meta[0]}" />`}).join('')}const code=escapeHtml(expressionCode(node));return`<div class="block-wrap ${expression?'expression-wrap':''}" data-id="${node.id}"><div class="block category-${d.type} ${d.type==='event'?'event':''} ${expression?'expression-block':''} ${state.selected===node.id?'selected':''}" style="background:${c.color}" draggable="true"><span class="block-icon">${d.icon}</span><span class="block-label">${labelFor(node.type)}</span>${inside}<button class="delete-mini" data-delete="${node.id}" title="Excluir">×</button></div>${d.children?`<div class="nested" data-parent="${node.id}">${(node.children||[]).map(child=>blockMarkup(child)).join('')}</div>`:''}${!expression&&state.inlineCode?`<code class="inline-code">${code}</code>`:''}</div>`}
function renderTree(){const root=$('treeRoot');root.innerHTML=state.tree.map(blockMarkup).join('');$('dropHint').style.display=state.tree.length?'none':'flex';$('blockCount').textContent=`${countNodes(state.tree)} bloco${countNodes(state.tree)===1?'':''}`;bindTree();updateCode()}
function countNodes(list){return list.reduce((n,x)=>n+1+(x.children?countNodes(x.children):0),0)}
function bindTree(){document.querySelectorAll('.block').forEach(el=>{el.onclick=e=>{if(e.target.matches('input,select,button,.socket'))return;state.selected=el.parentElement.dataset.id;renderTree();renderInspector()};el.ondragstart=e=>{e.stopPropagation();e.dataTransfer.setData('move-id',el.parentElement.dataset.id)};el.ondragover=e=>{e.preventDefault()};el.ondrop=e=>{e.preventDefault();e.stopPropagation();const key=e.dataTransfer.getData('block-key'),move=e.dataTransfer.getData('move-id');if(key)addNode(key,el.parentElement.dataset.id);else if(move)moveNode(move,el.parentElement.dataset.id)}});document.querySelectorAll('.nested').forEach(el=>{el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const key=e.dataTransfer.getData('block-key'),move=e.dataTransfer.getData('move-id');if(key)addNode(key,el.dataset.parent);else if(move)moveNode(move,el.dataset.parent)}});document.querySelectorAll('.socket').forEach(socket=>{socket.ondragover=e=>{e.preventDefault();socket.classList.add('socket-target')};socket.ondragleave=()=>socket.classList.remove('socket-target');socket.ondrop=e=>{e.preventDefault();e.stopPropagation();socket.classList.remove('socket-target');const key=e.dataTransfer.getData('block-key');if(key)addExpression(key,socket.dataset.socket,socket.dataset.prop)}});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();deleteNode(b.dataset.delete)});document.querySelectorAll('[data-prop]').forEach(input=>{input.onfocus=()=>snapshot();input.oninput=e=>{const found=findNode(state.tree,input.closest('[data-id]')?.dataset.id||state.selected);if(found){found.node.properties[input.dataset.prop]=input.value;updateCode()}}})}
function addExpression(key,parentId,property){const found=findNode(state.tree,parentId);if(!found)return;snapshot();const node=makeNode(key);found.node.properties[property]=node;state.selected=node.id;renderTree();renderInspector()}
function addNode(key,parentId=null){snapshot();const node=makeNode(key);if(parentId){const parent=findNode(state.tree,parentId);if(parent?.node.children)parent.node.children.push(node);else state.tree.push(node)}else state.tree.push(node);state.selected=node.id;renderTree();renderInspector()}
function deleteNode(id){snapshot();const found=findNode(state.tree,id);if(found){found.list.splice(found.list.indexOf(found.node),1);state.selected=null;renderTree();renderInspector()}}
function moveNode(id,targetId){if(id===targetId)return;snapshot();const source=findNode(state.tree,id);const target=findNode(state.tree,targetId);if(!source||!target||isDescendant(source.node,targetId))return;source.list.splice(source.list.indexOf(source.node),1);if(target.node.children)target.node.children.push(source.node);else state.tree.push(source.node);renderTree()}
function isDescendant(node,id){return(node.children||[]).some(x=>x.id===id||isDescendant(x,id))}
function renderInspector(){const found=state.selected&&findNode(state.tree,state.selected);if(!found){$('inspectorContent').innerHTML=`<div class="empty-inspector"><div>◌</div><strong>${state.language==='pt'?'Selecione um bloco':'Select a block'}</strong><span>${state.language==='pt'?'As propriedades aparecerão aqui':'Block properties appear here'}</span></div>`;return}const d=definitions[found.node.type],c=categories[d.type];const fields=Object.keys(d.propsMeta||{}).map(key=>{const meta=d.propsMeta[key];const value=found.node.properties[key]??'';if(meta[1]==='operator'||meta[1]==='type'){const options=meta[1]==='type'?['Número','Texto','Boolean']:['=','>','<','>=','<='];return`<div class="property"><label>${meta[0]}</label><select data-inspect="${key}">${options.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select></div>`}return`<div class="property"><label>${meta[0]}</label><input data-inspect="${key}" value="${escapeHtml(value)}" /></div>`}).join('');$('inspectorContent').innerHTML=`<div class="inspector-title"><div class="lib-icon" style="background:${c.color}">${d.icon}</div><strong>${labelFor(found.node.type)}</strong></div>${fields||`<div style="color:#9aa5b4;font-size:11px">${state.language==='pt'?'Este bloco não possui propriedades editáveis.':'This block has no editable properties.'}</div>`}`;document.querySelectorAll('[data-inspect]').forEach(input=>{input.onfocus=()=>snapshot();input.oninput=()=>{found.node.properties[input.dataset.inspect]=input.value;updateCode()}})}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]))}
function validate(){const errors=[];const vars=new Set();function walk(list){list.forEach(n=>{const d=definitions[n.type];Object.entries(n.properties||{}).forEach(([k,v])=>{if(typeof v!=='object'&&!String(v).trim())errors.push({id:n.id,msg:`${labelFor(n.type)}: ${d.propsMeta?.[k]?.[0]||k} ${state.language==='pt'?'vazio':'is empty'}`})});if(n.type==='createVar')vars.add(n.properties.name);walk(n.children||[])})}walk(state.tree);function second(list){list.forEach(n=>{if(['setVar','add','remove','useVar'].includes(n.type)&&!vars.has(n.properties.name))errors.push({id:n.id,msg:`${dLabel(n)}: ${state.language==='pt'?'variável':'variable'} "${n.properties.name||'?'}" ${state.language==='pt'?'não existe':'does not exist'}`});if(['if','logicIf'].includes(n.type)&&(!n.properties.left&&!n.properties.condition||n.type==='if'&&(!n.properties.operator||!n.properties.right)))errors.push({id:n.id,msg:state.language==='pt'?'Condição incompleta':'Incomplete condition'});if(n.children&&(['if','repeat','while','event'].includes(definitions[n.type].type)||n.type==='logicIf')&&n.children.length===0)errors.push({id:n.id,msg:`${dLabel(n)} ${state.language==='pt'?'precisa de blocos internos':'needs inner blocks'}`});second(n.children||[])})}second(state.tree);return errors}function dLabel(n){return labelFor(n.type)}
function generate(){const errors=validate();const grouped=new Map(errors.map(e=>[e.id,e]));document.querySelectorAll('.block-wrap').forEach(e=>e.classList.toggle('has-error',grouped.has(e.dataset.id)));$('errorsPanel').innerHTML=errors.length?`<div class="error-heading" style="color:#d86666"><span style="background:#ffe3e3">!</span><strong>${errors.length} erro${errors.length>1?'s':''} encontrado${errors.length>1?'s':''}</strong></div>${errors.slice(0,3).map(e=>`<div class="error-item"><span>!</span>${e.msg}</div>`).join('')}`:'<div class="error-heading"><span>✓</span><strong>Sem erros de validação</strong></div>';$('validState').innerHTML=errors.length?'<i style="background:#e66c6c"></i> '+errors.length+' erro(s)':'<i></i> válido';const lines=[];function emitList(list,depth=0){list.forEach(node=>emitNode(node,depth))}function emitNode(node,depth=0){const d=definitions[node.type];let line=d.template;Object.entries(node.properties||{}).forEach(([k,v])=>line=line.replaceAll(`{${k}}`,formatValue(node.type,k,v)));if(node.type==='else'){lines.push('  '.repeat(depth)+'else');emitList(node.children||[],depth+1);return}lines.push('  '.repeat(depth)+line);if(d.children){emitList(node.children||[],depth+1);if(node.type==='playerJoin'||node.type==='playerLeave'||node.type==='partTouched')lines.push('  '.repeat(depth)+'end)');else if(node.type==='gameStart')lines.push('  '.repeat(depth)+'end');else if(node.type!=='else')lines.push('  '.repeat(depth)+'end')}}emitList(state.tree);return lines.join('\n')||'-- Arraste blocos para gerar código Luau'}
function normalizeOperator(value){if(value===undefined||value===null) return '';const normalized=String(value).trim();if(normalized==='=') return '==';if(normalized==='==') return '==';if(normalized==='~=') return '~=';if(normalized==='≠') return '~=';return normalized}
function formatValue(type,key,value){if(key==='operator')return normalizeOperator(value);if(value&&typeof value==='object')return expressionCode(value);if(value==='any')return'nil';if(key==='text'||(key==='value'&&type==='print')||(key==='value'&&definitions[type].props?.valueType==='Texto'))return`"${String(value).replaceAll('"','\\"')}"`;if(key==='value'&&definitions[type].props?.valueType==='Boolean')return String(value).toLowerCase()==='true'?'true':'false';return value}
function expressionCode(node){const d=definitions[node.type];let line=d.template;Object.entries(node.properties||{}).forEach(([key,value])=>{line=line.replaceAll(`{${key}}`,formatValue(node.type,key,value))});return line}
function highlight(code){return escapeHtml(code).replace(/(&quot;.*?&quot;|&quot;.*)/g,'<span class="str">$1</span>').replace(/\b(local|function|then|do|end|while|for|in)\b/g,'<span class="kw">$1</span>').replace(/\b(\d+(?:\.\d+)?)\b/g,'<span class="num">$1</span>').replace(/\b(print|wait|Connect|FindFirstChildOfClass)\b/g,'<span class="fn">$1</span>')}
function updateCode(){const code=generate();$('codeOutput').innerHTML=highlight(code);$('lineCount').textContent=`${code.split('\n').length} linhas`}
function undo(){if(!state.history.length)return;state.future.push(clone(state.tree));state.tree=state.history.pop();state.selected=null;renderTree();renderInspector()}function redo(){if(!state.future.length)return;state.history.push(clone(state.tree));state.tree=state.future.pop();renderTree();renderInspector()}
$('canvas').ondragover=e=>e.preventDefault();$('canvas').ondrop=e=>{e.preventDefault();const key=e.dataTransfer.getData('block-key');if(key)addNode(key)};$('blockSearch').oninput=renderLibrary;$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('clearBtn').onclick=()=>{if(state.tree.length){snapshot();state.tree=[];state.selected=null;renderTree();renderInspector()}};$('copyBtn').onclick=()=>navigator.clipboard.writeText(generate()).then(()=>{showToast('Código Luau copiado');});$('runBtn').onclick=()=>{const errors=validate();showToast(errors.length?'Corrija os erros antes de testar':'Script pronto para testar no Roblox Studio')};$('renameProject').onclick=()=>{const name=prompt('Nome do script',$('projectTitle').textContent);if(name)$('projectTitle').textContent=name};$('zoomIn').onclick=()=>setZoom(state.zoom+10);$('zoomOut').onclick=()=>setZoom(state.zoom-10);$('gridToggle').onclick=()=>{state.grid=!state.grid;$('canvas').style.backgroundImage=state.grid?'radial-gradient(#d9e0e8 1px,transparent 1px)':'none'};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='z'){e.preventDefault();undo()}if((e.metaKey||e.ctrlKey)&&e.key==='y'){e.preventDefault();redo()}if(e.key==='Delete'&&state.selected)deleteNode(state.selected)});function setZoom(value){state.zoom=Math.max(70,Math.min(140,value));$('canvasInner').style.transform=`scale(${state.zoom/100})`;$('zoomValue').textContent=state.zoom+'%';$('statusZoom').textContent=state.zoom+'%'}function showToast(text){const t=$('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function duplicateNode(){if(!state.selected)return;const found=findNode(state.tree,state.selected);if(!found)return;snapshot();const copy=clone(found.node);function renew(node){node.id=crypto.randomUUID();(node.children||[]).forEach(renew)}renew(copy);found.list.splice(found.list.indexOf(found.node)+1,0,copy);state.selected=copy.id;renderTree();renderInspector();showToast('Bloco duplicado')}
$('duplicateBtn').onclick=duplicateNode;let hand=false,lastPoint=null;$('handTool').onclick=()=>{hand=!hand;$('handTool').classList.toggle('active',hand);$('selectTool').classList.toggle('active',!hand);$('canvas').style.cursor=hand?'grab':'default'};$('canvas').onpointerdown=e=>{if(!hand)return;lastPoint={x:e.clientX,y:e.clientY,scrollLeft:$('canvas').scrollLeft,scrollTop:$('canvas').scrollTop};$('canvas').setPointerCapture(e.pointerId)};$('canvas').onpointermove=e=>{if(!hand||!lastPoint)return;$('canvas').scrollLeft=lastPoint.scrollLeft-(e.clientX-lastPoint.x);$('canvas').scrollTop=lastPoint.scrollTop-(e.clientY-lastPoint.y)};$('canvas').onpointerup=()=>{lastPoint=null};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='d'){e.preventDefault();duplicateNode()}});
 $('languageBtn').onclick=()=>{state.language=state.language==='en'?'pt':'en';$('languageBtn').textContent=state.language==='en'?'PT':'EN';renderLibrary();renderTree();renderInspector()};$('inlineCodeBtn').onclick=()=>{state.inlineCode=!state.inlineCode;$('inlineCodeBtn').classList.toggle('active',state.inlineCode);renderTree()};$('themeBtn').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';document.body.classList.toggle('dark-theme',state.theme==='dark');$('themeBtn').textContent=state.theme==='dark'?'☀':'☾';$('themeBtn').title=state.theme==='dark'?'Usar tema claro':'Usar tema escuro'};bindTypingHub();resetTypingGame();renderLibrary();renderTree();renderInspector();
