const enumOptions = {
  KeyCode: [
    'None', 'Backspace', 'Tab', 'Clear', 'Return', 'Pause', 'Escape', 'Space',
    'Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
    'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'LeftShift', 'RightShift',
    'LeftControl', 'RightControl', 'LeftAlt', 'RightAlt', 'LeftMeta', 'RightMeta',
    'Up', 'Down', 'Left', 'Right', 'Insert', 'Delete', 'Home', 'End', 'PageUp',
    'PageDown', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11',
    'F12', 'NumLock', 'CapsLock', 'ScrollLock', 'ButtonA', 'ButtonB', 'ButtonX',
    'ButtonY', 'ButtonL1', 'ButtonR1', 'ButtonL2', 'ButtonR2', 'ButtonL3', 'ButtonR3',
    'ButtonStart', 'ButtonSelect', 'DPadUp', 'DPadDown', 'DPadLeft', 'DPadRight',
    'Thumbstick1', 'Thumbstick2', 'MouseLeftButton', 'MouseRightButton',
    'MouseMiddleButton', 'MouseWheel', 'MousePosition', 'TouchPosition',
  ],
  UserInputType: [
    'None', 'MouseButton1', 'MouseButton2', 'MouseButton3', 'MouseWheel',
    'MouseMovement', 'Keyboard', 'Touch', 'Focus', 'Accelerometer', 'Gyro',
    'Gamepad1', 'Gamepad2', 'Gamepad3', 'Gamepad4', 'TextInput',
  ],
  UserInputState: ['Begin', 'Change', 'End', 'Cancel', 'None'],
  HumanoidStateType: [
    'None', 'FallingDown', 'Ragdoll', 'GettingUp', 'Jumping', 'Swimming', 'Freefall',
    'Flying', 'Landed', 'Running', 'RunningNoPhysics', 'StrafingNoPhysics', 'Climbing',
    'Seated', 'PlatformStanding', 'Dead', 'Physics', 'Custom',
  ],
  HumanoidRigType: ['R6', 'R15'],
  Material: [
    'Plastic', 'SmoothPlastic', 'Neon', 'Wood', 'WoodPlanks', 'Marble', 'Basalt',
    'Slate', 'CrackedLava', 'Concrete', 'Limestone', 'Granite', 'Pavement', 'Brick',
    'Pebble', 'Cobblestone', 'Rock', 'Sandstone', 'CorrodedMetal', 'DiamondPlate',
    'Foil', 'Metal', 'Grass', 'LeafyGrass', 'Sand', 'Fabric', 'Snow', 'Mud', 'Ground',
    'Asphalt', 'Salt', 'Ice', 'Glacier', 'Glass', 'ForceField', 'Air', 'Water',
    'Cardboard', 'Carpet', 'CeramicTiles', 'ClayRoofTiles', 'RoofShingles', 'Leather',
    'Plaster', 'Rubber',
  ],
  PartType: ['Ball', 'Block', 'Cylinder', 'Wedge', 'CornerWedge'],
  EasingStyle: [
    'Linear', 'Sine', 'Back', 'Quad', 'Quart', 'Quint', 'Bounce', 'Elastic',
    'Exponential', 'Circular', 'Cubic',
  ],
  EasingDirection: ['In', 'Out', 'InOut'],
  CameraType: ['Fixed', 'Attach', 'Watch', 'Track', 'Follow', 'Custom', 'Scriptable', 'Orbital'],
  AnimationPriority: ['Core', 'Idle', 'Movement', 'Action', 'Action2', 'Action3', 'Action4'],
  RaycastFilterType: ['Exclude', 'Include'],
  ExplosionType: ['NoCraters', 'Craters'],
  TweenStatus: ['Canceled', 'Completed'],
  TextXAlignment: ['Left', 'Center', 'Right'],
  TextYAlignment: ['Top', 'Center', 'Bottom'],
  TextTruncate: ['None', 'AtEnd', 'SplitWord'],
  FillDirection: ['Horizontal', 'Vertical'],
  SortOrder: ['Name', 'LayoutOrder'],
  HorizontalAlignment: ['Left', 'Center', 'Right'],
  VerticalAlignment: ['Top', 'Center', 'Bottom'],
  ZIndexBehavior: ['Global', 'Sibling'],
  ScrollingDirection: ['X', 'Y', 'XY'],
  SurfaceType: [
    'Smooth', 'Glue', 'Weld', 'Studs', 'Inlet', 'Universal', 'Hinge', 'Motor',
    'SteppingMotor', 'SmoothNoOutlines', 'NoCollision',
  ],
  CollisionFidelity: ['Default', 'Hull', 'Box', 'PreciseConvexDecomposition'],
  ModelStreamingMode: ['Default', 'Atomic', 'Persistent', 'PersistentPerPlayer'],
  PhysicsSteppingMethod: ['Default', 'Fixed', 'Adaptive'],
  ActuatorRelativeTo: ['Attachment0', 'Attachment1', 'World'],
  PositionAlignmentMode: ['OneAttachment', 'TwoAttachment'],
  OrientationAlignmentMode: ['OneAttachment', 'TwoAttachment'],
  PathStatus: ['Success', 'NoPath', 'ClosestNoPath', 'ClosestOutOfRange'],
  FontSize: ['Size8', 'Size10', 'Size11', 'Size12', 'Size14', 'Size18', 'Size24', 'Size36', 'Size48'],
  FontStyle: ['Normal', 'Italic'],
  FormFactor: ['Symmetric', 'Brick', 'Plate'],
  GearType: [
    'Hat', 'Gear', 'MeleeWeapons', 'RangedWeapons', 'Explosives', 'PowerUps',
    'NavigationEnhancers', 'MusicalInstruments', 'SocialItems', 'BuildingTools', 'Transport',
  ],
  GamepadType: ['None', 'XboxOne', 'PS4', 'PS5', 'Windows', 'Unknown'],
  TeleportState: ['RequestedFromServer', 'Started', 'WaitingForServer', 'InProgress', 'Failed', 'Cancelled'],
  TeleportResult: ['Success', 'Failure', 'GameNotFound', 'GameEnded', 'GameFull', 'Unauthorized', 'Flooded'],
  ChatVersion: ['LegacyChatService', 'TextChatService'],
  TextFilterContext: ['PublicChat', 'PrivateChat'],
  PreferredInput: ['KeyboardAndMouse', 'Gamepad', 'Touch', 'MicroGamepad'],
  Axis: ['X', 'Y', 'Z'],
  AccessoryType: [
    'Unknown', 'Hat', 'Hair', 'Face', 'Neck', 'Shoulder', 'Front', 'Back', 'Waist',
    'TShirt', 'Shirt', 'Pants', 'Jacket', 'Sweater', 'Shorts', 'LeftShoe', 'RightShoe',
    'DressSkirt', 'Eyebrow', 'Eyelash',
  ],
  AvatarAssetType: [
    'TShirt', 'Shirt', 'Pants', 'Hat', 'Face', 'Head', 'Torso', 'LeftArm',
    'RightArm', 'LeftLeg', 'RightLeg',
  ],
  HighlightDepthMode: ['AlwaysOnTop', 'Occluded'],
  HandlesStyle: ['Resize', 'Movement'],
  HapticEffectType: [
    'None', 'Selection', 'Collision', 'Custom', 'UIHover', 'UIClick', 'UINotification',
    'GameplayExplosion', 'GameplayCollision',
  ],
  InOutInfoType: ['Input', 'Output'],
  InputType: ['Bool', 'Float', 'Vector2', 'NoInput', 'Constant', 'Sin'],
  InputActionType: ['Button', 'Axis1D', 'Axis2D', 'Axis3D'],
};

export const ROBLOX_ENUM_OPTIONS = Object.freeze(Object.fromEntries(
  Object.entries(enumOptions).map(([category, states]) => [category, Object.freeze(states)]),
));

export function getDefaultEnumState(category) {
  return ROBLOX_ENUM_OPTIONS[category]?.[0] ?? '';
}
